name: Remote Ansible Execution

on:
 workflow_dispatch:

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkfvQQ0yf8kVQlJ1/ODV4/ivF8XTY2vsBnb0fnjK1uTm8IVfgYy40Zfs4q9b66v4h5cv/VDRVd6gaeapjpnf6yElUZ54gF6q0jwxaESsfLB66G7SXJjh4iSa2oRRrycpWPMgth44c+NYPrhi77uuH6RIMtl2Lkhi75Zzdm66N5FvD9UjMZWabuuLu+gOmsNNgT2MAhDKX0mgBV8mug5Wda6tfLTllOseY4nOesUX/LDpdUfiK8Zo2zFdDRYVTnM8AW8sk6Rdb7N0F1hnwC8TseukD+RvKRv6ZB/ME/wlzgGLH+3fiIQprT0dHGK2Sk/22q4Dt6JnM/Uj20WwwcINBOn6PjycR7aVVXwhdHM05VhvkCbKL9UVPdh3QLkI9ej9oNmXmU9CilPRfNyP+WXFvKAmFo8VB4zGGM6yfzGT/GAmQe9z/1gvbQaJbZrEUeSHng2NO2WjCyp9qQl0aPSiQLOOIqGnz5TxS9YoLpJ2rHwnvngQTD7d+bbx/GZze0De8=" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 20.219.104.180 > ~/.ssh/known_hosts
  
      - name: Run Ansible on Remote Server
        run: ssh kingpin@20.219.104.180 'ansible-playbook /home/kingpin/rgcreate.yml'
