name: Create Repository from Template

on:
  workflow_dispatch:
    inputs:
      new_repo_name:
        description: 'Name of the new repository'
        required: true
      is_private:
        description: 'Should the new repo be private?'
        required: false
        default: 'true'

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository from Template
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_ReUse }}
        repository: your-username/template-repository
        event-type: create-repo
        client-payload: '{"name": "${{ github.event.inputs.new_repo_name }}", "private": ${{ github.event.inputs.is_private }}}'
